<a href="https://colab.research.google.com/github/NazHub1993/ML_Notebooks/blob/main/Book_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [315]:
import numpy as np
import pandas as pd

In [316]:
books=pd.read_csv('Books.csv')
users=pd.read_csv('Users.csv')
ratings=pd.read_csv('Ratings.csv')

/tmp/ipykernel_190/3397335393.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv('Books.csv')

In [317]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [318]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [319]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [320]:
books.shape

(271360, 8)

In [321]:
users.shape

(278858, 3)

In [322]:
ratings.shape

(1149780, 3)

In [323]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [324]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [325]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

#Popularity based recommendation system
#I will consider only the books that have got votes more than 250
#Then I will show the top 50 books means books with highest top 50 average rating

In [326]:
rating_with_books=ratings.merge(books,on='ISBN')
rating_with_books.drop_duplicates(inplace=True)
rating_with_books.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

#Let's find out the books that have number of book_ratings more than 250

#Book Titles based on number of ratings

In [327]:
number_of_ratings=rating_with_books.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [328]:
number_of_ratings.rename(columns={'Book-Rating':'num_rating'},inplace=True)

In [329]:
number_of_ratings.head(50)

                                           Book-Title  num_rating
0    A Light in the Storm: The Civil War Diary of ...           4
1                               Always Have Popsicles           1
2                Apple Magic (The Collector's series)           1
3    Ask Lily (Young Women of Faith: Lily Series, ...           1
4    Beyond IBM: Leadership Marketing and Finance ...           1
5    Clifford Visita El Hospital (Clifford El Gran...           1
6                                        Dark Justice           1
7                                            Deceived           2
8    Earth Prayers From around the World: 365 Pray...          10
9    Final Fantasy Anthology: Official Strategy Gu...           4
10   Flight of Fancy: American Heiresses (Zebra Ba...           2
11   Garfield Bigger and Better (Garfield (Numbere...           2
12                          God's Little Promise Book           2
13   Good Wives: Image and Reality in the Lives of...          10
14   Goosebumps Monster Edition 1: Welcome to Dead...           9
15   Harry Potter and the Bible: The Menace Behind...           1
16   Highland Desire (Zebra Splendor Historical Ro...           1
17   Hiking the California Coastal Trail: Oregon t...           1
18                                       It Takes Two           2
19               LA Gallinita Roja/the Little Red Hen           2
20   Little Comic Shop of Horrors (Give Yourself G...           4
21   Microsoft Application Architecture For Micros...           1
22   Murder of a Sleeping Beauty (Scumble River My...          11
23                                       Mystery Mile           2
24   Nonbook Materials: The Organization of Integr...           1
25     Pokemon: The Official Collector's Sticker Book           1
26   Q-Space (Star Trek The Next Generation, Book 47)          17
27    Q-Zone (Star Trek The Next Generation, Book 48)          11
28                  Stories of an Imaginary Childhood           1
29                 Summonings: Books of Magic, Vol. 2           2
30                       Tales of Terror and Suspense           1
31   The Secret of the Old Clock (Nancy Drew, Book 1)           3
32   The Tender Commandments : Reflections on the ...           2
33                      The Town Cats and Other Tales           1
34   This Place Has No Atmosphere (Laurel-Leaf Books)           9
35                                        Tough Loser           1
36   Travel Companion Chile and Easter Island (Tra...           1
37   Twenty Thousand Leagues Under the Sea (Illust...           1
38                                 Weird News Stories           2
39   Zap!: Science Fair Surprise! (Abracadabra!, B...           1
40                      the Devil Will Drag You Under           1
41                          !%@ (A Nutshell handbook)           2
42                    !Arriba! Comunicacion y cultura           2
43  !Trato hecho!: Spanish for Real Life, Combined...           1
44                                               !Yo!          11
45                 $14 In The Bank (Cathy Collection)           5
46                                    $30 Film School           1
47                                        $Weet Deal$           1
48  $oft Money: The True Power in Our Nation's Cap...           5
49       ' Allo 'Allo: the War Diaries of Rene Artois           1

#Book titles based on average rating

In [330]:
rating_with_books['Book-Rating'] = pd.to_numeric(rating_with_books['Book-Rating'], errors='coerce')
avg_ratings=rating_with_books.groupby('Book-Title').mean(numeric_only=True)['Book-Rating'].reset_index()
avg_ratings.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_ratings.head()

                                          Book-Title  avg_rating
0   A Light in the Storm: The Civil War Diary of ...        2.25
1                              Always Have Popsicles        0.00
2               Apple Magic (The Collector's series)        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...        8.00
4   Beyond IBM: Leadership Marketing and Finance ...        0.00

In [331]:
popular_df=number_of_ratings.merge(avg_ratings,on='Book-Title')

In [332]:
popular_df.head()

                                          Book-Title  num_rating  avg_rating
0   A Light in the Storm: The Civil War Diary of ...           4        2.25
1                              Always Have Popsicles           1        0.00
2               Apple Magic (The Collector's series)           1        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...           1        8.00
4   Beyond IBM: Leadership Marketing and Finance ...           1        0.00

In [333]:
popular_df=popular_df[popular_df['num_rating']>=250].sort_values('avg_rating',ascending=False).head(50)
popular_df.head()

,Book-Title,num_rating,avg_rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453

In [334]:
popular_df.shape

(50, 3)

#Now to get the book data I need to merge with books df again

In [335]:
popular_df=popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_rating','avg_rating']]

In [336]:
popular_df.head()

,Book-Title,Book-Author,Image-URL-M,num_rating,avg_rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453

In [337]:
popular_df.shape

(50, 5)

**#Popularity based recommendation project done!!!**
\

In [338]:
rating_with_books.drop_duplicates('Book-Title')

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031047,276688,0425150526,0,Death Crosses the Border,Janice Steinberg,1995,Berkley Publishing Group,http://images.amazon.com/images/P/0425150526.0...,http://images.amazon.com/images/P/0425150526.0...,http://images.amazon.com/images/P/0425150526.0...
1031056,276688,0449907422,0,Jazz Funeral: A Skip Langdon Novel,Julie Smith,1993,Ballantine Books,http://images.amazon.com/images/P/0449907422.0...,http://images.amazon.com/images/P/0449907422.0...,http://images.amazon.com/images/P/0449907422.0...
1031115,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031127,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031130,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

#Now starting the collaborative filtering based recommendation System

In [339]:
active_users=rating_with_books.groupby('User-ID').count()['Book-Rating']>200
active_users=active_users[active_users].index
active_users

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [340]:
filtered_rating=rating_with_books[rating_with_books['User-ID'].isin(active_users)]

In [341]:
filtered_rating.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...

In [342]:
famous_books=rating_with_books.groupby('Book-Title').count()['Book-Rating']>=50
famous_books=famous_books[famous_books].index
famous_books

Index(['10 Lb. Penalty', '16 Lighthouse Road', '1984', '1st to Die: A Novel',
       '2010: Odyssey Two', '204 Rosewood Lane', '2061: Odyssey Three',
       '24 Hours', '2nd Chance', '3rd Degree',
       ...
       'YOU BELONG TO ME', 'Year of Wonders', 'You Belong To Me',
       'You Shall Know Our Velocity', 'Young Wives',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"',
       '\Surely You're Joking, Mr. Feynman!\": Adventures of a Curious Character"',
       'stardust'],
      dtype='object', name='Book-Title', length=2444)

In [343]:
filter_rating=filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]
filter_rating.head()
filter_rating.shape

(112147, 10)

In [344]:
filter_rating=filter_rating.drop_duplicates()

In [362]:
filter_rating.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1157,277427,0060177721,0,Finding Moon,Tony Hillerman,1995,Harpercollins,http://images.amazon.com/images/P/0060177721.0...,http://images.amazon.com/images/P/0060177721.0...,http://images.amazon.com/images/P/0060177721.0...
1162,277427,006092988X,0,A Tree Grows in Brooklyn,Betty Smith,1998,Perennial,http://images.amazon.com/images/P/006092988X.0...,http://images.amazon.com/images/P/006092988X.0...,http://images.amazon.com/images/P/006092988X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1164,277427,0060932139,0,The Unbearable Lightness of Being : A Novel (P...,Milan Kundera,1999,Perennial,http://images.amazon.com/images/P/0060932139.0...,http://images.amazon.com/images/P/0060932139.0...,http://images.amazon.com/images/P/0060932139.0...

In [345]:
pt=filter_rating.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')
pt.fillna(0,inplace=True)
pt.shape

(2444, 811)

In [346]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
stardust,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [347]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(pt)
similarity.shape

(2444, 2444)

In [348]:
np.where(pt.index=='1984')[0][0]

np.int64(2)

In [349]:
sorted(list(enumerate(similarity[0])),key=lambda x:x[1],reverse=True)

[(0, np.float64(1.0)),
 (505, np.float64(0.530165026363713)),
 (707, np.float64(0.49980721032635916)),
 (2250, np.float64(0.49980721032635916)),
 (2067, np.float64(0.41586473646422367)),
 (1669, np.float64(0.3945239297317875)),
 (2169, np.float64(0.37614325833807666)),
 (1213, np.float64(0.3735605665432047)),
 (1038, np.float64(0.3710800935795249)),
 (1264, np.float64(0.36355624987385)),
 (1412, np.float64(0.32325614441111855)),
 (1181, np.float64(0.3085795057135766)),
 (2282, np.float64(0.2948420075240761)),
 (2227, np.float64(0.29110181672607033)),
 (21, np.float64(0.2909685675631574)),
 (977, np.float64(0.2885638274248393)),
 (1868, np.float64(0.2885638274248393)),
 (1395, np.float64(0.27615952827288226)),
 (724, np.float64(0.2740354543272148)),
 (1097, np.float64(0.2720605855696647)),
 (1685, np.float64(0.27125557922729093)),
 (281, np.float64(0.27113990412868194)),
 (265, np.float64(0.2682079330322221)),
 (126, np.float64(0.25830072144547395)),
 (127, np.float64(0.25179923489550915)),
 (1103, np.float64(0.25138088072129333)),
 (1768, np.float64(0.25131880370325305)),
 (109, np.float64(0.2507667011935206)),
 (775, np.float64(0.2461341039896772)),
 (1132, np.float64(0.24376252895075812)),
 (396, np.float64(0.23439374045767208)),
 (2078, np.float64(0.23273191657806622)),
 (1842, np.float64(0.22969765666933156)),
 (1229, np.float64(0.2274143425276894)),
 (1702, np.float64(0.22673173405393837)),
 (1169, np.float64(0.22661931140595826)),
 (121, np.float64(0.22138421144103998)),
 (1929, np.float64(0.21827032692450374)),
 (1677, np.float64(0.21620471732113994)),
 (606, np.float64(0.21589642155110206)),
 (1287, np.float64(0.21567529365234836)),
 (187, np.float64(0.2135896008588214)),
 (1034, np.float64(0.21323820644987304)),
 (143, np.float64(0.21099787561447372)),
 (1285, np.float64(0.21015427008877724)),
 (1743, np.float64(0.2082550795589195)),
 (634, np.float64(0.20717675418162443)),
 (1753, np.float64(0.20686823785324465)),
 (2209, np.float64(0.20647946687022686)),
 (391, np.float64(0.20639454831147583)),
 (1747, np.float64(0.20506149374767613)),
 (2171, np.float64(0.20485979500913676)),
 (1738, np.float64(0.2043116433859182)),
 (1173, np.float64(0.20425568698076121)),
 (2300, np.float64(0.20420471637733056)),
 (1540, np.float64(0.20336866968710027)),
 (1933, np.float64(0.20157206972005853)),
 (1529, np.float64(0.2006613664139348)),
 (1603, np.float64(0.19967852932242602)),
 (459, np.float64(0.19821723420526208)),
 (2202, np.float64(0.19771100788697107)),
 (453, np.float64(0.19754010912611497)),
 (1192, np.float64(0.19479580252835518)),
 (540, np.float64(0.19467011969539327)),
 (179, np.float64(0.19464187456869578)),
 (430, np.float64(0.19429545054547961)),
 (1043, np.float64(0.193033582201608)),
 (1898, np.float64(0.1923410872888311)),
 (91, np.float64(0.1916673157468957)),
 (294, np.float64(0.1914376364364156)),
 (1872, np.float64(0.18807162916903833)),
 (257, np.float64(0.18515234295713295)),
 (1019, np.float64(0.18174807648231242)),
 (653, np.float64(0.18161034967637174)),
 (2218, np.float64(0.18123952190138443)),
 (2295, np.float64(0.17873069351649465)),
 (1546, np.float64(0.1773942505701705)),
 (519, np.float64(0.1763469042641743)),
 (1122, np.float64(0.1753606229910031)),
 (412, np.float64(0.17456330301008802)),
 (882, np.float64(0.1715354522059553)),
 (111, np.float64(0.17127510913292468)),
 (674, np.float64(0.17103989486429005)),
 (1505, np.float64(0.16943282745921517)),
 (1836, np.float64(0.1694200893577002)),
 (190, np.float64(0.168328138300712)),
 (1970, np.float64(0.16787375482349778)),
 (1620, np.float64(0.16717669815946906)),
 (1877, np.float64(0.1666024034421197)),
 (1691, np.float64(0.166317466679033)),
 (2269, np.float64(0.16585193834990125)),
 (1141, np.float64(0.16578796579481012)),
 (79, np.float64(0.16517696654965577)),
 (2411, np.float64(0.16360031244323248)),
 (1269, np.float64(0.1635090939736691)),
 (491, np.float64(0.16336709733900504)),
 (1205, np.float64(0.1632766715477594)),
 (2042, np.float64(0.1631254193878777)),
 (1027, np.float64(0.16282978445559007)),
 (1841, np.float64(0.16192231616332656)),
 (991, np.float64(0.16156472590792512)),
 (264, np.float64(0.1614585618577112)),
 (1771, np.float64(0.16123337546938565)),
 (1495, np.float64(0.16052909313114785)),
 (1721, np.float64(0.16051988567015474)),
 (2115, np.float64(0.15977072071638446)),
 (1219, np.float64(0.15870200824897107)),
 (2230, np.float64(0.1580529175606124)),
 (1116, np.float64(0.1556688756904234)),
 (1750, np.float64(0.1545327463810354)),
 (1801, np.float64(0.1544646754417756)),
 (1023, np.float64(0.15367321233228246)),
 (2021, np.float64(0.15313177111288773)),
 (399, np.float64(0.1514644575890141)),
 (1339, np.float64(0.15120907300559566)),
 (1283, np.float64(0.1510591595757722)),
 (984, np.float64(0.15095188604257442)),
 (291, np.float64(0.1496100648760073)),
 (1326, np.float64(0.14854579372064208)),
 (1282, np.float64(0.14682758089278672)),
 (611, np.float64(0.14578960265629462)),
 (563, np.float64(0.14489929742123492)),
 (910, np.float64(0.14332954743852488)),
 (1044, np.float64(0.14280206009324548)),
 (2211, np.float64(0.14268666168666397)),
 (2345, np.float64(0.14256585829262144)),
 (1290, np.float64(0.14216878841372477)),
 (1752, np.float64(0.14209548474625963)),
 (268, np.float64(0.14179976021187962)),
 (567, np.float64(0.14119925240929976)),
 (1383, np.float64(0.14021047741448103)),
 (1532, np.float64(0.14017003191452962)),
 (248, np.float64(0.13992153476497032)),
 (2150, np.float64(0.13874687787089898)),
 (194, np.float64(0.13701247371855196)),
 (272, np.float64(0.13556041126753376)),
 (1255, np.float64(0.13554093839358894)),
 (1960, np.float64(0.13548257008324135)),
 (2309, np.float64(0.1348317646399188)),
 (2405, np.float64(0.13448268505189384)),
 (1857, np.float64(0.13447958855360267)),
 (1745, np.float64(0.13333635686776987)),
 (2274, np.float64(0.133023727230405)),
 (2343, np.float64(0.1320480526755633)),
 (1174, np.float64(0.13186035101326643)),
 (1061, np.float64(0.13176679984788006)),
 (2338, np.float64(0.13165305312871403)),
 (1782, np.float64(0.13148733654314382)),
 (1760, np.float64(0.13141774810929738)),
 (37, np.float64(0.13118514119283717)),
 (1904, np.float64(0.13112305240192643)),
 (287, np.float64(0.13083353203414183)),
 (1943, np.float64(0.13034599521780402)),
 (61, np.float64(0.12878710361895382)),
 (1758, np.float64(0.12869823736591302)),
 (1047, np.float64(0.12844296158758842)),
 (807, np.float64(0.1266804066822884)),
 (1744, np.float64(0.12643588340266532)),
 (1587, np.float64(0.1259191858157376)),
 (2104, np.float64(0.12587715565104238)),
 (1851, np.float64(0.1258588792985005)),
 (2416, np.float64(0.1256283863255829)),
 (365, np.float64(0.12544277422767305)),
 (1761, np.float64(0.12524261993448899)),
 (2341, np.float64(0.12513769191030327)),
 (1297, np.float64(0.12341307457724505)),
 (30, np.float64(0.12331122634669674)),
 (790, np.float64(0.12308709390425712)),
 (1088, np.float64(0.1229567332063795)),
 (570, np.float64(0.12238265296143896)),
 (1455, np.float64(0.12216886291130355)),
 (1273, np.float64(0.12195181602671555)),
 (2246, np.float64(0.12042127052237137)),
 (1491, np.float64(0.1200568030620097)),
 (2386, np.float64(0.11979294363709059)),
 (92, np.float64(0.11961355479659379)),
 (542, np.float64(0.11923368912191776)),
 (181, np.float64(0.11905234500309408)),
 (304, np.float64(0.11858022544989694)),
 (1939, np.float64(0.11825908035058479)),
 (988, np.float64(0.117714894856912)),
 (1069, np.float64(0.11714348225189222)),
 (819, np.float64(0.11712604430922671)),
 (2020, np.float64(0.11634893825701446)),
 (2151, np.float64(0.11594197887761164)),
 (1419, np.float64(0.11566181684868827)),
 (1798, np.float64(0.1154034233104405)),
 (36, np.float64(0.11511044209690935)),
 (101, np.float64(0.1149905295956352)),
 (2325, np.float64(0.11488780950000796)),
 (1633, np.float64(0.11478892921337994)),
 (1731, np.float64(0.11478573775083081)),
 (1964, np.float64(0.11398976458131094)),
 (1120, np.float64(0.11366854328968172)),
 (926, np.float64(0.11362189608970177)),
 (1582, np.float64(0.11355791315533816)),
 (814, np.float64(0.11316228526464288)),
 (1523, np.float64(0.11303626594507858)),
 (1378, np.float64(0.11198907261176554)),
 (993, np.float64(0.11187221800354608)),
 (2190, np.float64(0.11176028979342739)),
 (263, np.float64(0.11174603738122976)),
 (575, np.float64(0.11128138384038962)),
 (2116, np.float64(0.11100661574047524)),
 (985, np.float64(0.11057789893311827)),
 (2430, np.float64(0.11013377090136801)),
 (1511, np.float64(0.11003351313610255)),
 (1428, np.float64(0.10961600826445697)),
 (2415, np.float64(0.10952746761500984)),
 (301, np.float64(0.10886867949589323)),
 (2314, np.float64(0.10867942480347012)),
 (2052, np.float64(0.10848511663509902)),
 (296, np.float64(0.10609144820138246)),
 (1778, np.float64(0.10529321146827599)),
 (2006, np.float64(0.10455494229696323)),
 (2366, np.float64(0.1042444713601319)),
 (2284, np.float64(0.10303471599629085)),
 (2044, np.float64(0.10288368607279032)),
 (1979, np.float64(0.10285947529799391)),
 (1373, np.float64(0.10280381264638067)),
 (1772, np.float64(0.10268730810520257)),
 (1478, np.float64(0.10173066316137117)),
 (1545, np.float64(0.10165935436900986)),
 (1093, np.float64(0.1016506383442698)),
 (1962, np.float64(0.10036454590784336)),
 (93, np.float64(0.09996144206527184)),
 (2000, np.float64(0.09935499698140361)),
 (288, np.float64(0.09927496877914577)),
 (779, np.float64(0.09919513364859804)),
 (352, np.float64(0.09875945716867987)),
 (1104, np.float64(0.098517355586341)),
 (253, np.float64(0.09817772076740397)),
 (1437, np.float64(0.09786980511686244)),
 (1718, np.float64(0.09681195017240521)),
 (1421, np.float64(0.09662025001259629)),
 (1650, np.float64(0.09616321231835442)),
 (1469, np.float64(0.09596835780184708)),
 (343, np.float64(0.09480732628461007)),
 (75, np.float64(0.09470556052632924)),
 (791, np.float64(0.09446277557258873)),
 (931, np.float64(0.09372216241281997)),
 (1687, np.float64(0.0924387741287653)),
 (510, np.float64(0.09142844957482563)),
 (828, np.float64(0.09121627010084914)),
 (727, np.float64(0.09072115448846939)),
 (788, np.float64(0.09061137509024261)),
 (660, np.float64(0.09025457609033584)),
 (1781, np.float64(0.09017339222001808)),
 (2181, np.float64(0.08768547549585247)),
 (1766, np.float64(0.08765512924974697)),
 (153, np.float64(0.08723051279924636)),
 (2175, np.float64(0.08702587275880379)),
 (1324, np.float64(0.0869985425585201)),
 (2034, np.float64(0.08675260709347601)),
 (2112, np.float64(0.08615275319330651)),
 (1983, np.float64(0.0859977284631149)),
 (1268, np.float64(0.08555909595670964)),
 (1807, np.float64(0.0854856368391848)),
 (2342, np.float64(0.08545644553467704)),
 (1982, np.float64(0.08543464629671824)),
 (1216, np.float64(0.08438645145808021)),
 (1812, np.float64(0.08386390784443823)),
 (307, np.float64(0.08300478901373032)),
 (845, np.float64(0.08292596917495063)),
 (865, np.float64(0.08287942077432812)),
 (1917, np.float64(0.08277418630163498)),
 (1993, np.float64(0.082748630846792)),
 (722, np.float64(0.08271711653536011)),
 (784, np.float64(0.08262394494137872)),
 (38, np.float64(0.08232581676010438)),
 (564, np.float64(0.0818965118171287)),
 (945, np.float64(0.08158592230657345)),
 (1343, np.float64(0.08155163006206081)),
 (2185, np.float64(0.08041297141323847)),
 (328, np.float64(0.0798907585647976)),
 (444, np.float64(0.07924915450719983)),
 (970, np.float64(0.07908700772964125)),
 (169, np.float64(0.07857722681147886)),
 (135, np.float64(0.0774338496565066)),
 (378, np.float64(0.07725004749817194)),
 (2340, np.float64(0.07723930120980445)),
 (2326, np.float64(0.07616363648917215)),
 (1413, np.float64(0.07599927707204349)),
 (2278, np.float64(0.07560446068958547)),
 (88, np.float64(0.07533820341618196)),
 (316, np.float64(0.0740611922106269)),
 (956, np.float64(0.07400441049365018)),
 (339, np.float64(0.07393150870475088)),
 (2024, np.float64(0.0736285557724374)),
 (2096, np.float64(0.07349716786161911)),
 (1568, np.float64(0.07342834079644138)),
 (1770, np.float64(0.0720491160082087)),
 (1329, np.float64(0.07089988010593981)),
 (2161, np.float64(0.07077083894730127)),
 (1211, np.float64(0.07049221251530172)),
 (2160, np.float64(0.06967567285275106)),
 (2083, np.float64(0.06898400404766093)),
 (6, np.float64(0.0688604317430696)),
 (867, np.float64(0.06829235628931432)),
 (2139, np.float64(0.06814966572092758)),
 (2240, np.float64(0.06766795093245442)),
 (1894, np.float64(0.06725073521796021)),
 (2082, np.float64(0.06693496400088587)),
 (388, np.float64(0.06676313318160568)),
 (2143, np.float64(0.06664096137684788)),
 (2249, np.float64(0.0665345910594384)),
 (209, np.float64(0.06566985007337663)),
 (922, np.float64(0.06510384852034966)),
 (78, np.float64(0.06435334353093299)),
 (384, np.float64(0.06411063944774267)),
 (1817, np.float64(0.06372499303268281)),
 (1725, np.float64(0.06357505844177212)),
 (1233, np.float64(0.06296362064627985)),
 (1728, np.float64(0.06271833876083656)),
 (1776, np.float64(0.06237613153367691)),
 (1235, np.float64(0.0623078582164114)),
 (3, np.float64(0.0594470723373386)),
 (1327, np.float64(0.058724697779912724)),
 (792, np.float64(0.05836499073338329)),
 (1526, np.float64(0.05745320021606336)),
 (907, np.float64(0.05702686530447465)),
 (456, np.float64(0.0559481788403859)),
 (2441, np.float64(0.05547919829191863)),
 (1932, np.float64(0.054072415309329123)),
 (909, np.float64(0.053703208859650145)),
 (1321, np.float64(0.05362195093589015)),
 (2032, np.float64(0.052886690871275364)),
 (699, np.float64(0.051568324151815004)),
 (2312, np.float64(0.05139647596137905)),
 (1274, np.float64(0.050065302710900865)),
 (761, np.float64(0.049351093789670286)),
 (1131, np.float64(0.04897059933725024)),
 (1699, np.float64(0.048906686176134556)),
 (789, np.float64(0.04859645445836804)),
 (793, np.float64(0.04857819343923079)),
 (719, np.float64(0.04773618565302235)),
 (1999, np.float64(0.04745964731604005)),
 (1636, np.float64(0.04653531656097152)),
 (962, np.float64(0.046350028498903156)),
 (963, np.float64(0.04492932699468907)),
 (552, np.float64(0.043579236970302755)),
 (983, np.float64(0.043308641157072156)),
 (197, np.float64(0.04138331701508059)),
 (2193, np.float64(0.040282206007577134)),
 (644, np.float64(0.04016978479880353)),
 (521, np.float64(0.03966723891479041)),
 (147, np.float64(0.03852135278827664)),
 (1804, np.float64(0.03849419116311353)),
 (1862, np.float64(0.03709980164949561)),
 (1626, np.float64(0.03526223590317361)),
 (1110, np.float64(0.03490804977360069)),
 (1356, np.float64(0.029171980401425792)),
 (924, np.float64(0.027838173802978084)),
 (1934, np.float64(0.027320980921055844)),
 (2205, np.float64(0.02617455434482902)),
 (2359, np.float64(0.024181703679094713)),
 (518, np.float64(0.022340890304748957)),
 (955, np.float64(0.017573643443987954)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (4, np.float64(0.0)),
 (5, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0)),
 (10, np.float64(0.0)),
 (11, np.float64(0.0)),
 (12, np.float64(0.0)),
 (13, np.float64(0.0)),
 (14, np.float64(0.0)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0)),
 (19, np.float64(0.0)),
 (20, np.float64(0.0)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.0)),
 (25, np.float64(0.0)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (31, np.float64(0.0)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.0)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.0)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.0)),
 (50, np.float64(0.0)),
 (51, np.float64(0.0)),
 (52, np.float64(0.0)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.0)),
 (56, np.float64(0.0)),
 (57, np.float64(0.0)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.0)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.0)),
 (65, np.float64(0.0)),
 (66, np.float64(0.0)),
 (67, np.float64(0.0)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.0)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.0)),
 (76, np.float64(0.0)),
 (77, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.0)),
 (83, np.float64(0.0)),
 (84, np.float64(0.0)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.0)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.0)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.0)),
 (108, np.float64(0.0)),
 (110, np.float64(0.0)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.0)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.0)),
 (124, np.float64(0.0)),
 (125, np.float64(0.0)),
 (128, np.float64(0.0)),
 (129, np.float64(0.0)),
 (130, np.float64(0.0)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.0)),
 (140, np.float64(0.0)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.0)),
 (148, np.float64(0.0)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.0)),
 (152, np.float64(0.0)),
 (154, np.float64(0.0)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.0)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (164, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0)),
 (168, np.float64(0.0)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0)),
 (173, np.float64(0.0)),
 (174, np.float64(0.0)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (180, np.float64(0.0)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.0)),
 (195, np.float64(0.0)),
 (196, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.0)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.0)),
 (208, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (212, np.float64(0.0)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.0)),
 (221, np.float64(0.0)),
 (222, np.float64(0.0)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.0)),
 (230, np.float64(0.0)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),

In [360]:
def recommend(book_name):
  book_index=np.where(pt.index==book_name)[0][0]
  distances=similarity[book_index]
  similar_items=sorted(list(enumerate(distances)),key=lambda x:x[1],reverse=True)[1:10]

  for i in similar_items:
    print(pt.index[i[0]])

In [361]:
recommend('1984')

Lying Awake
The Restaurant at the End of the Universe (Hitchhiker's Trilogy (Paperback))
Waiting
Animal Farm
The Handmaid's Tale
Roll of Thunder, Hear My Cry
Awakening
A Portrait of the Artist As a Young Man
Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death

In [363]:
import pickle
pickle.dump(filter_rating,open('filter_rating.pkl','wb'))
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))