<a href="https://colab.research.google.com/github/NazHub1993/ML_Notebooks/blob/main/Naive_Bayes2(codebasics)%20%26%20Implementation_of_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
df=pd.read_csv('spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
df['Spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.head()

  Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [14]:
df.columns[df.isna().any()]

Index([], dtype='object')

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.25, random_state=42)

In [16]:
x_train[:10]

2005    Goodmorning, today i am late for  &lt;DECIMAL&...
4058                      Noice. Text me when you're here
2664    8007 FREE for 1st week! No1 Nokia tone 4 ur mo...
3387    Oops - am at my mum's in somerset... Bit far! ...
3978    Great NEW Offer - DOUBLE Mins & DOUBLE Txt on ...
93      Please call our customer service representativ...
3161                     How much did ur hdd casing cost.
1011    Lol I would but my mom would have a fit and te...
1425                    Yes.. now only saw your message..
2144    You stayin out of trouble stranger!!saw Dave t...
Name: Message, dtype: object

In [17]:
y_train[:40]

2005    0
4058    0
2664    1
3387    0
3978    1
93      1
3161    0
1011    0
1425    0
2144    0
3994    0
849     0
2861    0
2404    0
151     0
1728    0
2704    0
3506    0
1279    0
134     1
1527    0
3058    0
3512    0
88      0
3367    0
3543    0
2520    0
3535    0
5193    0
3934    0
5343    0
4335    0
5469    0
4960    0
4758    0
3811    0
2161    0
842     0
3763    1
4922    0
Name: Spam, dtype: int64

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_count=v.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [20]:
x_test_count=v.transform(x_test)
model.score(x_test_count,y_test)

0.9863603732950467

#Now how do you make work the whole thing using a pipeline?

In [24]:
from sklearn.pipeline import Pipeline
clf=Pipeline(
    [
        ('vectorizer',CountVectorizer()),
        ('nb',MultinomialNB())
    ]
)

In [25]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [26]:
clf.score(x_test,y_test)

0.9863603732950467